### ISSUE TITLE
Update On PyCharm

### ISSUE THREAD

**Issue by AmaOwusua** [AmaOwusua/python#1]
When I make changes( eg: creating a readme file) on git. How do I update it on PyCharm?

**Comment by AmaOwusua** [comment]
I clicked on update project on PyCharm . I guess that is the right way to do it. 
![image](https://user-images.githubusercontent.com/102427677/162011795-4ac2e585-42a5-40ab-a7a6-7a690e1f4a8c.png)

**Comment by aappau** [comment]
Yhup, I think it's the same as using `git pull` in the CLI

**Comment by AmaOwusua** [comment]
oh ok.
Was having some errors when i was trying to pull with the CLI but i am figuring it out now.
Thanks.
